services:
  ts-api:
    build: ./apis/api-ts
    container_name: my-ts-api
    labels:
      app: ts-api
      lang: ts
    environment:
      - SERVER_PORT=3060
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "3060:3060"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  java-api:
    build: ./apis/api-java
    container_name: my-java-api
    labels:
      app: java-api
      lang: java
    environment:
      - SERVER_PORT=3070
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "3070:3070"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  go-api:
    build: ./apis/api-go
    container_name: my-go-api
    labels:
      app: go-api
      lang: go
    environment:
      - SERVER_PORT=3080
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "3080:3080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  k6:
    image: grafana/k6
    depends_on:
      - go-api
      - java-api
      - ts-api
      - prometheus
    volumes:
      - ./k6:/k6
    working_dir: /k6
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(50),p(95),p(99),avg,min,max
    # command: ["run", "-o", "experimental-prometheus-rw", "/k6/scripts/smoke.js"]
    entrypoint: ["k6"]