{
 "title": "bachelor",
 "time": { "from": "2026-02-04T13:32:00.000Z", "to": "2026-02-04T13:37:10.000Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "api",
    "label": "API",
    "query": {
     "query": "label_values(k6_http_req_duration_p99,api)"
    }
   },
   { "name": "route", "label": "Route", "query": { "query": "label_values(route)" } }
  ]
 },
 "panels": [
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "VUS" }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (api) (rate(k6_http_reqs_total[10s]))",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{container_label_app=~\"java-api|go-api|ts-api\"}[10s])",
     "legendFormat": "{{container_label_app}}"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * container_memory_working_set_bytes{container_label_app=~\"java-api|go-api|ts-api\"} / container_spec_memory_limit_bytes{container_label_app=~\"java-api|go-api|ts-api\"}",
     "legendFormat": "{{container_label_app}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_app=~\"java-api|go-api|ts-api\"}",
     "legendFormat": "{{container_label_app}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (api) (\r\n  avg_over_time(k6_http_req_duration_avg[10s])\r\n)\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (api) (\r\n  max_over_time(k6_http_req_duration_p99{api=~\"$api\", route=~\"$route\"}[10s])\r\n)",
     "legendFormat": "P99 – {{api}}"
    },
    {
     "expr": "max by (api) (\r\n  max_over_time(k6_http_req_duration_p95{api=~\"$api\", route=~\"$route\"}[10s])\r\n)\r\n",
     "legendFormat": "P95 – {{api}}"
    },
    {
     "expr": "max by (api) (\r\n  max_over_time(k6_http_req_duration_p50{api=~\"$api\", route=~\"$route\"}[10s])\r\n)",
     "legendFormat": "P50 – {{api}}"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n  (\r\n    (\r\n      sum by (api) (rate(k6_http_reqs_total{status=~\"0|4..|5..\"}[10s]))\r\n      OR on (api)\r\n      (0 * sum by (api) (rate(k6_http_reqs_total[10s])))\r\n    )\r\n    /\r\n    sum by (api) (rate(k6_http_reqs_total[10s]))\r\n  )\r\n)\r\n",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}